/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './footer.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './footer.component.css.shim';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/core/src/security';
var renderType_FooterComponent_Host:import0.RenderComponentType = (null as any);
class _View_FooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FooterComponent_0_4:import3.FooterComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FooterComponent_Host0,renderType_FooterComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-footer',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FooterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FooterComponent_0_4 = new import3.FooterComponent();
    this._appEl_0.initComponent(this._FooterComponent_0_4,[],compView_0);
    compView_0.create(this._FooterComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FooterComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FooterComponent_Host === (null as any))) { (renderType_FooterComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_FooterComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FooterComponentNgFactory:import9.ComponentFactory<import3.FooterComponent> = new import9.ComponentFactory<import3.FooterComponent>('app-footer',viewFactory_FooterComponent_Host0,import3.FooterComponent);
const styles_FooterComponent:any[] = [import10.styles];
var renderType_FooterComponent:import0.RenderComponentType = (null as any);
class _View_FooterComponent0 extends import1.AppView<import3.FooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import11.RouterLinkWithHref;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _RouterLinkWithHref_13_3:import11.RouterLinkWithHref;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _RouterLinkWithHref_17_3:import11.RouterLinkWithHref;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _arr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  _arr_2:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FooterComponent0,renderType_FooterComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','footer');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-lg-12');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','nav nav-pills nav-justified');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'li',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','col-lg-4');
    this._el_9 = this.renderer.createElement(this._el_8,'a',(null as any));
    this._RouterLinkWithHref_9_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_10 = this.renderer.createText(this._el_9,'©2016 GoWhere.com',(null as any));
    this._text_11 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_6,'li',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-lg-4');
    this._el_13 = this.renderer.createElement(this._el_12,'a',(null as any));
    this._RouterLinkWithHref_13_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_14 = this.renderer.createText(this._el_13,'Terms of Service',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_6,'li',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','col-lg-4');
    this._el_17 = this.renderer.createElement(this._el_16,'a',(null as any));
    this._RouterLinkWithHref_17_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_18 = this.renderer.createText(this._el_17,'Privacy',(null as any));
    this._text_19 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_4,'\n         ',(null as any));
    this._text_21 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._arr_2 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3; }
    if (((token === import11.RouterLinkWithHref) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkWithHref_13_3; }
    if (((token === import11.RouterLinkWithHref) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkWithHref_17_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_9_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_9_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = this._arr_1('/');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_13_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_13_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = this._arr_2('/');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_17_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_17_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_9_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_9,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._RouterLinkWithHref_13_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_13,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._RouterLinkWithHref_17_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_17,'href',this.viewUtils.sanitizer.sanitize(import15.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_9_3.ngOnDestroy();
    this._RouterLinkWithHref_13_3.ngOnDestroy();
    this._RouterLinkWithHref_17_3.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_9_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_13_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_17_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FooterComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FooterComponent> {
  if ((renderType_FooterComponent === (null as any))) { (renderType_FooterComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/footer/footer.component.html',0,import8.ViewEncapsulation.Emulated,styles_FooterComponent,{})); }
  return new _View_FooterComponent0(viewUtils,parentInjector,declarationEl);
}