/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.footer[_ngcontent-%COMP%] {\n    margin-top: 5%;\n    margin-bottom: 1%;\n    font-size: 12px;\n}\n\n.nav.nav-pills.nav-justified[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    color: #a2a2a0;\n}\n\n.nav.nav-pills.nav-justified[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n    background: #141414;\n    color: white;\n}\n\n.nav.nav-pills.nav-justified[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:focus {\n    background: #141414;\n}'];