/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './act-input.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './act.service';
import * as import9 from '../auth/auth.service';
import * as import10 from '../errors/error.service';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import15 from '@angular/forms/src/directives/ng_control_status';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/forms/src/directives/default_value_accessor';
import * as import18 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
import * as import24 from '@angular/core/src/security';
var renderType_ActInputComponent_Host:import0.RenderComponentType = (null as any);
class _View_ActInputComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ActInputComponent_0_4:import3.ActInputComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent_Host0,renderType_ActInputComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-act-input',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ActInputComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ActInputComponent_0_4 = new import3.ActInputComponent(this.parentInjector.get(import8.ActService),this.parentInjector.get(import9.AuthService),this.parentInjector.get(import10.ErrorService),this.parentInjector.get(import11.Router));
    this._appEl_0.initComponent(this._ActInputComponent_0_4,[],compView_0);
    compView_0.create(this._ActInputComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ActInputComponent) && (0 === requestNodeIndex))) { return this._ActInputComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ActInputComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ActInputComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ActInputComponent_Host === (null as any))) { (renderType_ActInputComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_ActInputComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ActInputComponentNgFactory:import13.ComponentFactory<import3.ActInputComponent> = new import13.ComponentFactory<import3.ActInputComponent>('app-act-input',viewFactory_ActInputComponent_Host0,import3.ActInputComponent);
const styles_ActInputComponent:any[] = ['h3[_ngcontent-%COMP%] {\n            color: white;\n        }\n        label[_ngcontent-%COMP%], span[_ngcontent-%COMP%] {\n            color: white;\n        }\n        input.ng-invalid.ng-touched[_ngcontent-%COMP%] {\n            border: 1px solid red;\n            color: darkred;\n        }\n        textarea.ng-invalid.ng-touched[_ngcontent-%COMP%] {\n            border: 1px solid red;\n            color: darkred;\n        }\n        span.danger[_ngcontent-%COMP%] {\n            color: #D23029;\n        }\n        article.popDown[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n            margin-bottom: 30px;\n        }\n        \n        img[_ngcontent-%COMP%] {\n            height: 222px;\n            width: 350px;\n        }\n\n        .imagePreview[_ngcontent-%COMP%] {\n            padding: 0;\n        }\n        \n        button[_ngcontent-%COMP%] {\n            margin: 15px;\n        }\n\n        .rightSide[_ngcontent-%COMP%] {\n            padding: auto 15px;\n        }'];
var renderType_ActInputComponent:import0.RenderComponentType = (null as any);
class _View_ActInputComponent0 extends import1.AppView<import3.ActInputComponent> {
  _text_0:any;
  _el_1:any;
  _FormGroupDirective_1_3:import14.FormGroupDirective;
  _ControlContainer_1_4:any;
  _NgControlStatusGroup_1_5:import15.NgControlStatusGroup;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import16.NgIf;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import16.NgIf;
  _text_22:any;
  _el_23:any;
  _DefaultValueAccessor_23_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_23_4:any[];
  _FormControlName_23_5:import18.FormControlName;
  _NgControl_23_6:any;
  _NgControlStatus_23_7:import15.NgControlStatus;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_31_4:any[];
  _FormControlName_31_5:import18.FormControlName;
  _NgControl_31_6:any;
  _NgControlStatus_31_7:import15.NgControlStatus;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _DefaultValueAccessor_39_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_39_4:any[];
  _FormControlName_39_5:import18.FormControlName;
  _NgControl_39_6:any;
  _NgControlStatus_39_7:import15.NgControlStatus;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _TemplateRef_47_5:any;
  _NgIf_47_6:import16.NgIf;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _TemplateRef_49_5:any;
  _NgIf_49_6:import16.NgIf;
  _text_50:any;
  _el_51:any;
  _DefaultValueAccessor_51_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_51_4:any[];
  _FormControlName_51_5:import18.FormControlName;
  _NgControl_51_6:any;
  _NgControlStatus_51_7:import15.NgControlStatus;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _DefaultValueAccessor_60_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_60_4:any[];
  _FormControlName_60_5:import18.FormControlName;
  _NgControl_60_6:any;
  _NgControlStatus_60_7:import15.NgControlStatus;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _DefaultValueAccessor_68_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_68_4:any[];
  _FormControlName_68_5:import18.FormControlName;
  _NgControl_68_6:any;
  _NgControlStatus_68_7:import15.NgControlStatus;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _DefaultValueAccessor_76_3:import17.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_76_4:any[];
  _FormControlName_76_5:import18.FormControlName;
  _NgControl_76_6:any;
  _NgControlStatus_76_7:import15.NgControlStatus;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _el_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _text_105:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_85:any;
  /*private*/ _expr_86:any;
  /*private*/ _expr_87:any;
  /*private*/ _expr_88:any;
  /*private*/ _expr_89:any;
  /*private*/ _expr_90:any;
  /*private*/ _expr_91:any;
  /*private*/ _expr_92:any;
  /*private*/ _expr_93:any;
  /*private*/ _expr_95:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent0,renderType_ActInputComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n\n\n\n\n\n\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._FormGroupDirective_1_3 = new import14.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_1_4 = this._FormGroupDirective_1_3;
    this._NgControlStatusGroup_1_5 = new import15.NgControlStatusGroup(this._ControlContainer_1_4);
    this._text_2 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','container-fluid');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'section',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','container');
    this._text_6 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','container-page');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'h1',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Create Event',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'				\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-md-6');
    this._text_13 = this.renderer.createText(this._el_12,'\n				\n				',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','form-group col-lg-12');
    this._text_15 = this.renderer.createText(this._el_14,'\n					',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'label',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Title',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n					',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_19 = new import2.AppElement(19,14,this,this._anchor_19);
    this._TemplateRef_19_5 = new import19.TemplateRef_(this._appEl_19,viewFactory_ActInputComponent1);
    this._NgIf_19_6 = new import16.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_21 = new import2.AppElement(21,14,this,this._anchor_21);
    this._TemplateRef_21_5 = new import19.TemplateRef_(this._appEl_21,viewFactory_ActInputComponent2);
    this._NgIf_21_6 = new import16.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_14,'input',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','form-control');
    this.renderer.setElementAttribute(this._el_23,'formControlName','title');
    this.renderer.setElementAttribute(this._el_23,'id','title');
    this.renderer.setElementAttribute(this._el_23,'placeholder','e.g. Mega Sale @Ion Orchard');
    this.renderer.setElementAttribute(this._el_23,'type','text');
    this._DefaultValueAccessor_23_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_23));
    this._NG_VALUE_ACCESSOR_23_4 = [this._DefaultValueAccessor_23_3];
    this._FormControlName_23_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_23_4);
    this._NgControl_23_6 = this._FormControlName_23_5;
    this._NgControlStatus_23_7 = new import15.NgControlStatus(this._NgControl_23_6);
    this._text_24 = this.renderer.createText(this._el_14,'\n				',(null as any));
    this._text_25 = this.renderer.createText(this._el_12,'\n				\n				',(null as any));
    this._el_26 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-group col-lg-6');
    this._text_27 = this.renderer.createText(this._el_26,'\n					',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'label',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Start Date & Time',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n					',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'input',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','form-control');
    this.renderer.setElementAttribute(this._el_31,'formControlName','starttime');
    this.renderer.setElementAttribute(this._el_31,'id','starttime');
    this.renderer.setElementAttribute(this._el_31,'type','datetime-local');
    this._DefaultValueAccessor_31_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_31));
    this._NG_VALUE_ACCESSOR_31_4 = [this._DefaultValueAccessor_31_3];
    this._FormControlName_31_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_31_4);
    this._NgControl_31_6 = this._FormControlName_31_5;
    this._NgControlStatus_31_7 = new import15.NgControlStatus(this._NgControl_31_6);
    this._text_32 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._text_33 = this.renderer.createText(this._el_12,'\n				\n				',(null as any));
    this._el_34 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','form-group col-lg-6');
    this._text_35 = this.renderer.createText(this._el_34,'\n					',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'label',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'End Date & Time',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n					',(null as any));
    this._el_39 = this.renderer.createElement(this._el_34,'input',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','form-control');
    this.renderer.setElementAttribute(this._el_39,'formControlName','endtime');
    this.renderer.setElementAttribute(this._el_39,'id','endtime');
    this.renderer.setElementAttribute(this._el_39,'type','datetime-local');
    this._DefaultValueAccessor_39_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_39));
    this._NG_VALUE_ACCESSOR_39_4 = [this._DefaultValueAccessor_39_3];
    this._FormControlName_39_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_39_4);
    this._NgControl_39_6 = this._FormControlName_39_5;
    this._NgControlStatus_39_7 = new import15.NgControlStatus(this._NgControl_39_6);
    this._text_40 = this.renderer.createText(this._el_34,'\n				',(null as any));
    this._text_41 = this.renderer.createText(this._el_12,'\n\n                 ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','form-group col-lg-6');
    this._text_43 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'label',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Details ',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_42,(null as any));
    this._appEl_47 = new import2.AppElement(47,42,this,this._anchor_47);
    this._TemplateRef_47_5 = new import19.TemplateRef_(this._appEl_47,viewFactory_ActInputComponent3);
    this._NgIf_47_6 = new import16.NgIf(this._appEl_47.vcRef,this._TemplateRef_47_5);
    this._text_48 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_42,(null as any));
    this._appEl_49 = new import2.AppElement(49,42,this,this._anchor_49);
    this._TemplateRef_49_5 = new import19.TemplateRef_(this._appEl_49,viewFactory_ActInputComponent4);
    this._NgIf_49_6 = new import16.NgIf(this._appEl_49.vcRef,this._TemplateRef_49_5);
    this._text_50 = this.renderer.createText(this._el_42,'\n                    ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_42,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','form-control');
    this.renderer.setElementAttribute(this._el_51,'formControlName','details');
    this.renderer.setElementAttribute(this._el_51,'id','details');
    this.renderer.setElementAttribute(this._el_51,'placeholder','Details');
    this.renderer.setElementAttribute(this._el_51,'rows','4');
    this._DefaultValueAccessor_51_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_51));
    this._NG_VALUE_ACCESSOR_51_4 = [this._DefaultValueAccessor_51_3];
    this._FormControlName_51_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_51_4);
    this._NgControl_51_6 = this._FormControlName_51_5;
    this._NgControlStatus_51_7 = new import15.NgControlStatus(this._NgControl_51_6);
    this._text_52 = this.renderer.createText(this._el_51,'                    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._text_54 = this.renderer.createText(this._el_12,'\n								\n				',(null as any));
    this._el_55 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','form-group col-lg-6');
    this._text_56 = this.renderer.createText(this._el_55,'\n					',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'label',(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'Location of Event',(null as any));
    this._text_59 = this.renderer.createText(this._el_55,'\n					',(null as any));
    this._el_60 = this.renderer.createElement(this._el_55,'input',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','form-control');
    this.renderer.setElementAttribute(this._el_60,'formControlName','address');
    this.renderer.setElementAttribute(this._el_60,'id','address');
    this.renderer.setElementAttribute(this._el_60,'placeholder','e.g. 8 Claymore Hill');
    this.renderer.setElementAttribute(this._el_60,'type','text');
    this._DefaultValueAccessor_60_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_60));
    this._NG_VALUE_ACCESSOR_60_4 = [this._DefaultValueAccessor_60_3];
    this._FormControlName_60_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_60_4);
    this._NgControl_60_6 = this._FormControlName_60_5;
    this._NgControlStatus_60_7 = new import15.NgControlStatus(this._NgControl_60_6);
    this._text_61 = this.renderer.createText(this._el_55,'\n				',(null as any));
    this._text_62 = this.renderer.createText(this._el_12,'\n				\n				',(null as any));
    this._el_63 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','form-group col-lg-6');
    this._text_64 = this.renderer.createText(this._el_63,'\n					',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'label',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Event Website URL',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n					',(null as any));
    this._el_68 = this.renderer.createElement(this._el_63,'input',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','form-control');
    this.renderer.setElementAttribute(this._el_68,'formControlName','websiteurl');
    this.renderer.setElementAttribute(this._el_68,'id','websiteurl');
    this.renderer.setElementAttribute(this._el_68,'placeholder','e.g. https://www.gowhere.com.sg');
    this.renderer.setElementAttribute(this._el_68,'type','text');
    this._DefaultValueAccessor_68_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_68));
    this._NG_VALUE_ACCESSOR_68_4 = [this._DefaultValueAccessor_68_3];
    this._FormControlName_68_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_68_4);
    this._NgControl_68_6 = this._FormControlName_68_5;
    this._NgControlStatus_68_7 = new import15.NgControlStatus(this._NgControl_68_6);
    this._text_69 = this.renderer.createText(this._el_63,'\n				',(null as any));
    this._text_70 = this.renderer.createText(this._el_12,'\n\n                ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','form-group col-lg-12');
    this._text_72 = this.renderer.createText(this._el_71,'\n					',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'label',(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'Image',(null as any));
    this._text_75 = this.renderer.createText(this._el_71,'\n					',(null as any));
    this._el_76 = this.renderer.createElement(this._el_71,'input',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','form-control');
    this.renderer.setElementAttribute(this._el_76,'formControlName','thumbnail');
    this.renderer.setElementAttribute(this._el_76,'id','thumbnail');
    this.renderer.setElementAttribute(this._el_76,'placeholder','Image URL: .jpg/.png/.jpeg');
    this.renderer.setElementAttribute(this._el_76,'type','text');
    this._DefaultValueAccessor_76_3 = new import17.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_76));
    this._NG_VALUE_ACCESSOR_76_4 = [this._DefaultValueAccessor_76_3];
    this._FormControlName_76_5 = new import18.FormControlName(this._ControlContainer_1_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_76_4);
    this._NgControl_76_6 = this._FormControlName_76_5;
    this._NgControlStatus_76_7 = new import15.NgControlStatus(this._NgControl_76_6);
    this._text_77 = this.renderer.createText(this._el_71,'\n				',(null as any));
    this._text_78 = this.renderer.createText(this._el_12,'\n\n			',(null as any));
    this._text_79 = this.renderer.createText(this._el_7,'\n		\n			',(null as any));
    this._el_80 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','rightSide col-md-6');
    this._text_81 = this.renderer.createText(this._el_80,'\n				',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'label',(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'Image Preview',(null as any));
    this._text_84 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_80,'br',(null as any));
    this._el_86 = this.renderer.createElement(this._el_80,'br',(null as any));
    this._text_87 = this.renderer.createText(this._el_80,'\n                ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_88,'class','imagePreview col-md-6');
    this._text_89 = this.renderer.createText(this._el_88,'\n                    ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_88,'img',(null as any));
    this.renderer.setElementAttribute(this._el_90,'alt','Image Preview');
    this.renderer.setElementAttribute(this._el_90,'class','image');
    this._text_91 = this.renderer.createText(this._el_88,'\n                ',(null as any));
    this._text_92 = this.renderer.createText(this._el_80,'\n            ',(null as any));
    this._text_93 = this.renderer.createText(this._el_7,'\n\n		',(null as any));
    this._text_94 = this.renderer.createText(this._el_5,'\n\n                ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','buttonBelow col-md-12');
    this._text_96 = this.renderer.createText(this._el_95,'\n                    ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_95,'button',(null as any));
    this.renderer.setElementAttribute(this._el_97,'class','btn btn-danger col-md-2');
    this.renderer.setElementAttribute(this._el_97,'type','button');
    this._text_98 = this.renderer.createText(this._el_97,'Reset Fields\n                    ',(null as any));
    this._text_99 = this.renderer.createText(this._el_95,'		\n                    ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_95,'button',(null as any));
    this.renderer.setElementAttribute(this._el_100,'class','btn btn-success col-md-3');
    this.renderer.setElementAttribute(this._el_100,'type','submit');
    this._text_101 = this.renderer.createText(this._el_100,'Post Event\n                    ',(null as any));
    this._text_102 = this.renderer.createText(this._el_95,'\n                ',(null as any));
    this._text_103 = this.renderer.createText(this._el_5,'\n\n	',(null as any));
    this._text_104 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_105 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'ngSubmit',this.eventHandler(this._handle_ngSubmit_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'submit',this.eventHandler(this._handle_submit_1_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_1,'reset',this.eventHandler(this._handle_reset_1_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_1_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_1_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_23,'keyup',this.eventHandler(this._handle_keyup_23_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_23,'input',this.eventHandler(this._handle_input_23_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_23,'blur',this.eventHandler(this._handle_blur_23_2.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_31,'keyup',this.eventHandler(this._handle_keyup_31_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_31,'input',this.eventHandler(this._handle_input_31_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_31,'blur',this.eventHandler(this._handle_blur_31_2.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_39,'keyup',this.eventHandler(this._handle_keyup_39_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_39,'input',this.eventHandler(this._handle_input_39_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_39,'blur',this.eventHandler(this._handle_blur_39_2.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_51,'keyup',this.eventHandler(this._handle_keyup_51_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_51,'input',this.eventHandler(this._handle_input_51_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_51,'blur',this.eventHandler(this._handle_blur_51_2.bind(this)));
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_60,'input',this.eventHandler(this._handle_input_60_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_60,'blur',this.eventHandler(this._handle_blur_60_1.bind(this)));
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    var disposable_17:Function = this.renderer.listen(this._el_68,'input',this.eventHandler(this._handle_input_68_0.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_68,'blur',this.eventHandler(this._handle_blur_68_1.bind(this)));
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_75 = import7.UNINITIALIZED;
    this._expr_76 = import7.UNINITIALIZED;
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
    var disposable_19:Function = this.renderer.listen(this._el_76,'keyup',this.eventHandler(this._handle_keyup_76_0.bind(this)));
    var disposable_20:Function = this.renderer.listen(this._el_76,'input',this.eventHandler(this._handle_input_76_1.bind(this)));
    var disposable_21:Function = this.renderer.listen(this._el_76,'blur',this.eventHandler(this._handle_blur_76_2.bind(this)));
    this._expr_85 = import7.UNINITIALIZED;
    this._expr_86 = import7.UNINITIALIZED;
    this._expr_87 = import7.UNINITIALIZED;
    this._expr_88 = import7.UNINITIALIZED;
    this._expr_89 = import7.UNINITIALIZED;
    this._expr_90 = import7.UNINITIALIZED;
    this._expr_91 = import7.UNINITIALIZED;
    this._expr_92 = import7.UNINITIALIZED;
    this._expr_93 = import7.UNINITIALIZED;
    var disposable_22:Function = this.renderer.listen(this._el_97,'click',this.eventHandler(this._handle_click_97_0.bind(this)));
    this._expr_95 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._text_105
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19,
      disposable_20,
      disposable_21,
      disposable_22
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import16.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import19.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import16.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import17.DefaultValueAccessor) && (23 === requestNodeIndex))) { return this._DefaultValueAccessor_23_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (23 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_23_4; }
    if (((token === import18.FormControlName) && (23 === requestNodeIndex))) { return this._FormControlName_23_5; }
    if (((token === import22.NgControl) && (23 === requestNodeIndex))) { return this._NgControl_23_6; }
    if (((token === import15.NgControlStatus) && (23 === requestNodeIndex))) { return this._NgControlStatus_23_7; }
    if (((token === import17.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_4; }
    if (((token === import18.FormControlName) && (31 === requestNodeIndex))) { return this._FormControlName_31_5; }
    if (((token === import22.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_6; }
    if (((token === import15.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_7; }
    if (((token === import17.DefaultValueAccessor) && (39 === requestNodeIndex))) { return this._DefaultValueAccessor_39_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (39 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_39_4; }
    if (((token === import18.FormControlName) && (39 === requestNodeIndex))) { return this._FormControlName_39_5; }
    if (((token === import22.NgControl) && (39 === requestNodeIndex))) { return this._NgControl_39_6; }
    if (((token === import15.NgControlStatus) && (39 === requestNodeIndex))) { return this._NgControlStatus_39_7; }
    if (((token === import19.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import16.NgIf) && (47 === requestNodeIndex))) { return this._NgIf_47_6; }
    if (((token === import19.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import16.NgIf) && (49 === requestNodeIndex))) { return this._NgIf_49_6; }
    if (((token === import17.DefaultValueAccessor) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._DefaultValueAccessor_51_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NG_VALUE_ACCESSOR_51_4; }
    if (((token === import18.FormControlName) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._FormControlName_51_5; }
    if (((token === import22.NgControl) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgControl_51_6; }
    if (((token === import15.NgControlStatus) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._NgControlStatus_51_7; }
    if (((token === import17.DefaultValueAccessor) && (60 === requestNodeIndex))) { return this._DefaultValueAccessor_60_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (60 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_60_4; }
    if (((token === import18.FormControlName) && (60 === requestNodeIndex))) { return this._FormControlName_60_5; }
    if (((token === import22.NgControl) && (60 === requestNodeIndex))) { return this._NgControl_60_6; }
    if (((token === import15.NgControlStatus) && (60 === requestNodeIndex))) { return this._NgControlStatus_60_7; }
    if (((token === import17.DefaultValueAccessor) && (68 === requestNodeIndex))) { return this._DefaultValueAccessor_68_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (68 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_68_4; }
    if (((token === import18.FormControlName) && (68 === requestNodeIndex))) { return this._FormControlName_68_5; }
    if (((token === import22.NgControl) && (68 === requestNodeIndex))) { return this._NgControl_68_6; }
    if (((token === import15.NgControlStatus) && (68 === requestNodeIndex))) { return this._NgControlStatus_68_7; }
    if (((token === import17.DefaultValueAccessor) && (76 === requestNodeIndex))) { return this._DefaultValueAccessor_76_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (76 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_76_4; }
    if (((token === import18.FormControlName) && (76 === requestNodeIndex))) { return this._FormControlName_76_5; }
    if (((token === import22.NgControl) && (76 === requestNodeIndex))) { return this._NgControl_76_6; }
    if (((token === import15.NgControlStatus) && (76 === requestNodeIndex))) { return this._NgControlStatus_76_7; }
    if (((token === import14.FormGroupDirective) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._FormGroupDirective_1_3; }
    if (((token === import23.ControlContainer) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._ControlContainer_1_4; }
    if (((token === import15.NgControlStatusGroup) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 105)))) { return this._NgControlStatusGroup_1_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_1_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_1_3.ngOnChanges(changes); }
    const currVal_10:any = ((this.context.titlechar > 0) && (this.context.titlechar < 6));
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_19_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = (this.context.titlechar < (0 - 34));
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_21_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    changes = (null as any);
    const currVal_15:any = 'title';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._FormControlName_23_5.name = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = ((this.context.act == (null as any))? (null as any): this.context.act.title);
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._FormControlName_23_5.model = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._FormControlName_23_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_28:any = 'starttime';
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._FormControlName_31_5.name = currVal_28;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_28,currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = ((this.context.act == (null as any))? (null as any): this.context.act.starttime);
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this._FormControlName_31_5.model = currVal_29;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_29,currVal_29);
      this._expr_29 = currVal_29;
    }
    if ((changes !== (null as any))) { this._FormControlName_31_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_41:any = 'endtime';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._FormControlName_39_5.name = currVal_41;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_41,currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = ((this.context.act == (null as any))? (null as any): this.context.act.endtime);
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._FormControlName_39_5.model = currVal_42;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_42,currVal_42);
      this._expr_42 = currVal_42;
    }
    if ((changes !== (null as any))) { this._FormControlName_39_5.ngOnChanges(changes); }
    const currVal_49:any = ((this.context.detailschar > 0) && (this.context.detailschar < 50));
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this._NgIf_47_6.ngIf = currVal_49;
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = (this.context.detailschar < (0 - 350));
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._NgIf_49_6.ngIf = currVal_50;
      this._expr_50 = currVal_50;
    }
    changes = (null as any);
    const currVal_54:any = 'details';
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this._FormControlName_51_5.name = currVal_54;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_54,currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = ((this.context.act == (null as any))? (null as any): this.context.act.details);
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this._FormControlName_51_5.model = currVal_55;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_55,currVal_55);
      this._expr_55 = currVal_55;
    }
    if ((changes !== (null as any))) { this._FormControlName_51_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_64:any = 'address';
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this._FormControlName_60_5.name = currVal_64;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_64,currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = ((this.context.act == (null as any))? (null as any): this.context.act.address);
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this._FormControlName_60_5.model = currVal_65;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_65,currVal_65);
      this._expr_65 = currVal_65;
    }
    if ((changes !== (null as any))) { this._FormControlName_60_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_74:any = 'websiteurl';
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this._FormControlName_68_5.name = currVal_74;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_74,currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = ((this.context.act == (null as any))? (null as any): this.context.act.websiteurl);
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this._FormControlName_68_5.model = currVal_75;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_75,currVal_75);
      this._expr_75 = currVal_75;
    }
    if ((changes !== (null as any))) { this._FormControlName_68_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_85:any = 'thumbnail';
    if (import4.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this._FormControlName_76_5.name = currVal_85;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_85,currVal_85);
      this._expr_85 = currVal_85;
    }
    const currVal_86:any = ((this.context.act == (null as any))? (null as any): this.context.act.thumbnail);
    if (import4.checkBinding(throwOnChange,this._expr_86,currVal_86)) {
      this._FormControlName_76_5.model = currVal_86;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_86,currVal_86);
      this._expr_86 = currVal_86;
    }
    if ((changes !== (null as any))) { this._FormControlName_76_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_1_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_1_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_1,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_1_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_1,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_1_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_1,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_1_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_1,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_1_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_1,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_17:any = this._NgControlStatus_23_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_23_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_23_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_23_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_23_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_23_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_26:any = this.context.mindateinput;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementProperty(this._el_31,'min',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this.context.maxdateinput;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementProperty(this._el_31,'max',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_30:any = this._NgControlStatus_31_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_31,'ng-untouched',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_31_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_31,'ng-touched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_31_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_31,'ng-pristine',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_31_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_31,'ng-dirty',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_31_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_31,'ng-valid',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_31_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_31,'ng-invalid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_39:any = this.context.mindateinput;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementProperty(this._el_39,'min',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this.context.maxdateinput;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementProperty(this._el_39,'max',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_43:any = this._NgControlStatus_39_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_39,'ng-untouched',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_39_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_39,'ng-touched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_39_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_39,'ng-pristine',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_39_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_39,'ng-dirty',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_39_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_39,'ng-valid',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_39_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_39,'ng-invalid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_56:any = this._NgControlStatus_51_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_51,'ng-untouched',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_51_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_51,'ng-touched',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_51_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_51,'ng-pristine',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_51_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_51,'ng-dirty',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._NgControlStatus_51_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_51,'ng-valid',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = this._NgControlStatus_51_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_51,'ng-invalid',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_66:any = this._NgControlStatus_60_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_60,'ng-untouched',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_60_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_60,'ng-touched',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_60_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_60,'ng-pristine',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_60_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_60,'ng-dirty',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_60_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_60,'ng-valid',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_71:any = this._NgControlStatus_60_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_60,'ng-invalid',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_76:any = this._NgControlStatus_68_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setElementClass(this._el_68,'ng-untouched',currVal_76);
      this._expr_76 = currVal_76;
    }
    const currVal_77:any = this._NgControlStatus_68_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementClass(this._el_68,'ng-touched',currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = this._NgControlStatus_68_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementClass(this._el_68,'ng-pristine',currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:any = this._NgControlStatus_68_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementClass(this._el_68,'ng-dirty',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this._NgControlStatus_68_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_68,'ng-valid',currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = this._NgControlStatus_68_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementClass(this._el_68,'ng-invalid',currVal_81);
      this._expr_81 = currVal_81;
    }
    const currVal_87:any = this._NgControlStatus_76_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_87,currVal_87)) {
      this.renderer.setElementClass(this._el_76,'ng-untouched',currVal_87);
      this._expr_87 = currVal_87;
    }
    const currVal_88:any = this._NgControlStatus_76_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_88,currVal_88)) {
      this.renderer.setElementClass(this._el_76,'ng-touched',currVal_88);
      this._expr_88 = currVal_88;
    }
    const currVal_89:any = this._NgControlStatus_76_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_89,currVal_89)) {
      this.renderer.setElementClass(this._el_76,'ng-pristine',currVal_89);
      this._expr_89 = currVal_89;
    }
    const currVal_90:any = this._NgControlStatus_76_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_90,currVal_90)) {
      this.renderer.setElementClass(this._el_76,'ng-dirty',currVal_90);
      this._expr_90 = currVal_90;
    }
    const currVal_91:any = this._NgControlStatus_76_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_91,currVal_91)) {
      this.renderer.setElementClass(this._el_76,'ng-valid',currVal_91);
      this._expr_91 = currVal_91;
    }
    const currVal_92:any = this._NgControlStatus_76_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_92,currVal_92)) {
      this.renderer.setElementClass(this._el_76,'ng-invalid',currVal_92);
      this._expr_92 = currVal_92;
    }
    const currVal_93:any = import4.interpolate(1,'',this.context.thumbnailinput,'');
    if (import4.checkBinding(throwOnChange,this._expr_93,currVal_93)) {
      this.renderer.setElementProperty(this._el_90,'src',this.viewUtils.sanitizer.sanitize(import24.SecurityContext.URL,currVal_93));
      this._expr_93 = currVal_93;
    }
    const currVal_95:boolean = !this.context.myForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_95,currVal_95)) {
      this.renderer.setElementProperty(this._el_100,'disabled',currVal_95);
      this._expr_95 = currVal_95;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_23_5.ngOnDestroy();
    this._FormControlName_31_5.ngOnDestroy();
    this._FormControlName_39_5.ngOnDestroy();
    this._FormControlName_51_5.ngOnDestroy();
    this._FormControlName_60_5.ngOnDestroy();
    this._FormControlName_68_5.ngOnDestroy();
    this._FormControlName_76_5.ngOnDestroy();
  }
  private _handle_ngSubmit_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_1_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_1_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_1_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_23_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_23_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_31_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_31_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_31_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_31_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_39_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_39_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_39_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_39_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_51_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_51_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_51_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_51_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_51_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_60_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_60_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_60_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_60_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_68_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_68_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_68_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_68_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_76_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_76_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_76_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_76_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_76_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_97_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClear()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ActInputComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ActInputComponent> {
  if ((renderType_ActInputComponent === (null as any))) { (renderType_ActInputComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/acts/act-input.component.html',0,import12.ViewEncapsulation.Emulated,styles_ActInputComponent,{})); }
  return new _View_ActInputComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ActInputComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent1,renderType_ActInputComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'(char left: ',this.parent.context.titlechar,')');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ActInputComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ActInputComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ActInputComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent2,renderType_ActInputComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','danger');
    this._text_1 = this.renderer.createText(this._el_0,'(max char: 40)',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ActInputComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ActInputComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ActInputComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent3,renderType_ActInputComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'(char left: ',this.parent.context.detailschar,')');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ActInputComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ActInputComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ActInputComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ActInputComponent4,renderType_ActInputComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','danger');
    this._text_1 = this.renderer.createText(this._el_0,'(max char: 400)',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ActInputComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ActInputComponent4(viewUtils,parentInjector,declarationEl);
}