/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './main.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './act.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './main.component.css.shim';
import * as import12 from '@angular/common/src/directives/ng_for';
import * as import13 from '../footer/footer.component';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '../footer/footer.component.ngfactory';
import * as import17 from './act-thumbnail/act-thumbnail.component';
import * as import18 from './act-thumbnail/act-thumbnail.component.ngfactory';
import * as import19 from '../auth/auth.service';
var renderType_MainComponent_Host:import0.RenderComponentType = (null as any);
class _View_MainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MainComponent_0_4:import3.MainComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainComponent_Host0,renderType_MainComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-home-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MainComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MainComponent_0_4 = new import3.MainComponent(this.parentInjector.get(import8.ActService));
    this._appEl_0.initComponent(this._MainComponent_0_4,[],compView_0);
    compView_0.create(this._MainComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MainComponent) && (0 === requestNodeIndex))) { return this._MainComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MainComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MainComponent_Host === (null as any))) { (renderType_MainComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MainComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MainComponentNgFactory:import10.ComponentFactory<import3.MainComponent> = new import10.ComponentFactory<import3.MainComponent>('my-home-app',viewFactory_MainComponent_Host0,import3.MainComponent);
const styles_MainComponent:any[] = [import11.styles];
var renderType_MainComponent:import0.RenderComponentType = (null as any);
class _View_MainComponent0 extends import1.AppView<import3.MainComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _anchor_108:any;
  /*private*/ _appEl_108:import2.AppElement;
  _TemplateRef_108_5:any;
  _NgFor_108_6:import12.NgFor;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _el_112:any;
  /*private*/ _appEl_112:import2.AppElement;
  _FooterComponent_112_4:import13.FooterComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainComponent0,renderType_MainComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-md-12');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','carousel slide');
    this.renderer.setElementAttribute(this._el_6,'data-ride','carousel');
    this.renderer.setElementAttribute(this._el_6,'id','carousel-example-generic');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_8 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_6,'ol',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','carousel-indicators');
    this._text_10 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'li',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','active');
    this.renderer.setElementAttribute(this._el_11,'data-slide-to','0');
    this.renderer.setElementAttribute(this._el_11,'data-target','#carousel-example-generic');
    this._text_12 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_9,'li',(null as any));
    this.renderer.setElementAttribute(this._el_13,'data-slide-to','1');
    this.renderer.setElementAttribute(this._el_13,'data-target','#carousel-example-generic');
    this._text_14 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_9,'li',(null as any));
    this.renderer.setElementAttribute(this._el_15,'data-slide-to','2');
    this.renderer.setElementAttribute(this._el_15,'data-target','#carousel-example-generic');
    this._text_16 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_18 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','carousel-inner');
    this._text_20 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','item active');
    this._text_22 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'img',(null as any));
    this.renderer.setElementAttribute(this._el_23,'alt','First slide');
    this.renderer.setElementAttribute(this._el_23,'class','c');
    this.renderer.setElementAttribute(this._el_23,'src','https://www.6am-group.com/wp-content/uploads/2016/08/Festival-Crowd--e1472160900369.jpg');
    this._text_24 = this.renderer.createText(this._el_21,'\n                        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_21,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','carousel-caption');
    this._text_26 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'h3',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Ultra Music Festival',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n                            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_25,'p',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Marina Bay',(null as any));
    this._text_32 = this.renderer.createText(this._el_25,'\n                        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','item');
    this._text_36 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'img',(null as any));
    this.renderer.setElementAttribute(this._el_37,'alt','Second slide');
    this.renderer.setElementAttribute(this._el_37,'class','c');
    this.renderer.setElementAttribute(this._el_37,'src','https://thecolorrun.com.au/wp-content/uploads/2015/08/Home-Page-IMAGE01.jpg');
    this._text_38 = this.renderer.createText(this._el_35,'\n                        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','carousel-caption');
    this._text_40 = this.renderer.createText(this._el_39,'\n                            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'h3',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Colour Run',(null as any));
    this._text_43 = this.renderer.createText(this._el_39,'\n                            ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_39,'p',(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Sentosa',(null as any));
    this._text_46 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._text_48 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_19,'div',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','item');
    this._text_50 = this.renderer.createText(this._el_49,'\n                        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'img',(null as any));
    this.renderer.setElementAttribute(this._el_51,'alt','Third slide');
    this.renderer.setElementAttribute(this._el_51,'class','c');
    this.renderer.setElementAttribute(this._el_51,'src','https://singaporefinest.com.sg/wp-content/uploads/2016/01/2015_Chingay-2015_Hi-Res_02-Afur-Wong.jpg');
    this._text_52 = this.renderer.createText(this._el_49,'\n                        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_49,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','carousel-caption');
    this._text_54 = this.renderer.createText(this._el_53,'\n                            ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'h3',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Chingay Parade Singapore',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n                            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_53,'p',(null as any));
    this._text_59 = this.renderer.createText(this._el_58,'F1 Pit Building',(null as any));
    this._text_60 = this.renderer.createText(this._el_53,'\n                        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_49,'\n                    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_63 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_6,'a',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','left carousel-control');
    this.renderer.setElementAttribute(this._el_64,'data-slide','prev');
    this.renderer.setElementAttribute(this._el_64,'href','#carousel-example-generic');
    this._text_65 = this.renderer.createText(this._el_64,'\n                    ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'span',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','glyphicon glyphicon-chevron-left');
    this._text_67 = this.renderer.createText(this._el_6,'\n                    \n                    ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_6,'a',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','right carousel-control');
    this.renderer.setElementAttribute(this._el_68,'data-slide','next');
    this.renderer.setElementAttribute(this._el_68,'href','#carousel-example-generic');
    this._text_69 = this.renderer.createText(this._el_68,'\n                    ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_68,'span',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','glyphicon glyphicon-chevron-right');
    this._text_71 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_72 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_73 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','main-text hidden-xs');
    this._text_75 = this.renderer.createText(this._el_74,'\n                ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'div',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','col-md-12 text-center');
    this._text_77 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_76,'h1',(null as any));
    this._text_79 = this.renderer.createText(this._el_78,'Organise a successful event.',(null as any));
    this._text_80 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_76,'h3',(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'Spread the word.',(null as any));
    this._text_83 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_76,'div',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','');
    this._text_85 = this.renderer.createText(this._el_84,'\n                        ',(null as any));
    this._text_86 = this.renderer.createText(this._el_84,'\n                ',(null as any));
    this._text_87 = this.renderer.createText(this._el_76,'\n            ',(null as any));
    this._text_88 = this.renderer.createText(this._el_74,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_90 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_91 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_92 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_92,'id','push');
    this._text_93 = this.renderer.createText(this._el_92,'\n',(null as any));
    this._text_94 = this.renderer.createText(this._el_0,'\n\n\n\n\n\n\n',(null as any));
    this._el_95 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_95,'class','container');
    this._text_96 = this.renderer.createText(this._el_95,'    \n  ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_95,'div',(null as any));
    this.renderer.setElementAttribute(this._el_97,'class','row');
    this._text_98 = this.renderer.createText(this._el_97,'\n\n    ',(null as any));
    this._el_99 = this.renderer.createElement(this._el_97,'div',(null as any));
    this.renderer.setElementAttribute(this._el_99,'class','row');
    this._text_100 = this.renderer.createText(this._el_99,'\n      ',(null as any));
    this._el_101 = this.renderer.createElement(this._el_99,'div',(null as any));
    this.renderer.setElementAttribute(this._el_101,'class','col-md-12');
    this._text_102 = this.renderer.createText(this._el_101,'\n        ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_101,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_103,'class','header col-md-12');
    this._text_104 = this.renderer.createText(this._el_103,'All Events',(null as any));
    this._text_105 = this.renderer.createText(this._el_101,'  \n      ',(null as any));
    this._text_106 = this.renderer.createText(this._el_99,'\n    ',(null as any));
    this._text_107 = this.renderer.createText(this._el_97,'\n\n    ',(null as any));
    this._anchor_108 = this.renderer.createTemplateAnchor(this._el_97,(null as any));
    this._appEl_108 = new import2.AppElement(108,97,this,this._anchor_108);
    this._TemplateRef_108_5 = new import14.TemplateRef_(this._appEl_108,viewFactory_MainComponent1);
    this._NgFor_108_6 = new import12.NgFor(this._appEl_108.vcRef,this._TemplateRef_108_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_109 = this.renderer.createText(this._el_97,'\n\n  ',(null as any));
    this._text_110 = this.renderer.createText(this._el_95,'\n',(null as any));
    this._text_111 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._el_112 = this.renderer.createElement(this._el_0,'app-footer',(null as any));
    this._appEl_112 = new import2.AppElement(112,0,this,this._el_112);
    var compView_112:any = import16.viewFactory_FooterComponent0(this.viewUtils,this.injector(112),this._appEl_112);
    this._FooterComponent_112_4 = new import13.FooterComponent();
    this._appEl_112.initComponent(this._FooterComponent_112_4,[],compView_112);
    compView_112.create(this._FooterComponent_112_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._anchor_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._el_112
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (108 === requestNodeIndex))) { return this._TemplateRef_108_5; }
    if (((token === import12.NgFor) && (108 === requestNodeIndex))) { return this._NgFor_108_6; }
    if (((token === import13.FooterComponent) && (112 === requestNodeIndex))) { return this._FooterComponent_112_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.acts;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_108_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_108_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_108_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MainComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MainComponent> {
  if ((renderType_MainComponent === (null as any))) { (renderType_MainComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/acts/main.component.html',0,import9.ViewEncapsulation.Emulated,styles_MainComponent,{})); }
  return new _View_MainComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MainComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ActThumbnailComponent_0_4:import17.ActThumbnailComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MainComponent1,renderType_MainComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'act-thumbnail',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import18.viewFactory_ActThumbnailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ActThumbnailComponent_0_4 = new import17.ActThumbnailComponent(this.parent.parentInjector.get(import8.ActService),this.parent.parentInjector.get(import19.AuthService));
    this._appEl_0.initComponent(this._ActThumbnailComponent_0_4,[],compView_0);
    compView_0.create(this._ActThumbnailComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.ActThumbnailComponent) && (0 === requestNodeIndex))) { return this._ActThumbnailComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ActThumbnailComponent_0_4.act = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MainComponent1(viewUtils,parentInjector,declarationEl);
}