/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['h3.col-md-3[_ngcontent-%COMP%] {\n    color: white;\n}\n\nimg.c[_ngcontent-%COMP%] {\n    height: 500px;\n    width: 1200px;\n    object-fit: cover;\n}\n\n\n.main-text[_ngcontent-%COMP%]\n{\n    position: absolute;\n    top: 50px;\n    width: 96.66666666666666%;\n    color: #FFF;\n}\n.btn-min-block[_ngcontent-%COMP%]\n{\n    min-width: 170px;\n    line-height: 26px;\n}\n.btn-clear[_ngcontent-%COMP%]\n{\n    color: #FFF;\n    background-color: transparent;\n    border-color: #FFF;\n    margin-right: 15px;\n}\n.btn-clear[_ngcontent-%COMP%]:hover\n{\n    color: #000;\n    background-color: #FFF;\n}'];