/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './signup.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './signup.component.css.shim';
import * as import13 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from '@angular/forms/src/directives/default_value_accessor';
import * as import16 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from '@angular/core/src/linker/template_ref';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/control_container';
var renderType_SignupComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignupComponent_0_4:import3.SignupComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent_Host0,renderType_SignupComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-signup',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupComponent_0_4 = new import3.SignupComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._SignupComponent_0_4,[],compView_0);
    compView_0.create(this._SignupComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignupComponent) && (0 === requestNodeIndex))) { return this._SignupComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SignupComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignupComponent_Host === (null as any))) { (renderType_SignupComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SignupComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupComponentNgFactory:import11.ComponentFactory<import3.SignupComponent> = new import11.ComponentFactory<import3.SignupComponent>('app-signup',viewFactory_SignupComponent_Host0,import3.SignupComponent);
const styles_SignupComponent:any[] = [import12.styles];
var renderType_SignupComponent:import0.RenderComponentType = (null as any);
class _View_SignupComponent0 extends import1.AppView<import3.SignupComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _FormGroupDirective_6_3:import13.FormGroupDirective;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import14.NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _FormControlName_13_5:import16.FormControlName;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import14.NgControlStatus;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import17.NgIf;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import17.NgIf;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_25_4:any[];
  _FormControlName_25_5:import16.FormControlName;
  _NgControl_25_6:any;
  _NgControlStatus_25_7:import14.NgControlStatus;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _DefaultValueAccessor_34_3:import15.DefaultValueAccessor;
  _RadioControlValueAccessor_34_4:import18.RadioControlValueAccessor;
  _NG_VALUE_ACCESSOR_34_5:any[];
  _FormControlName_34_6:import16.FormControlName;
  _NgControl_34_7:any;
  _NgControlStatus_34_8:import14.NgControlStatus;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _DefaultValueAccessor_38_3:import15.DefaultValueAccessor;
  _RadioControlValueAccessor_38_4:import18.RadioControlValueAccessor;
  _NG_VALUE_ACCESSOR_38_5:any[];
  _FormControlName_38_6:import16.FormControlName;
  _NgControl_38_7:any;
  _NgControlStatus_38_8:import14.NgControlStatus;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _anchor_48:any;
  /*private*/ _appEl_48:import2.AppElement;
  _TemplateRef_48_5:any;
  _NgIf_48_6:import17.NgIf;
  _text_49:any;
  _anchor_50:any;
  /*private*/ _appEl_50:import2.AppElement;
  _TemplateRef_50_5:any;
  _NgIf_50_6:import17.NgIf;
  _text_51:any;
  _el_52:any;
  _DefaultValueAccessor_52_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_52_4:any[];
  _FormControlName_52_5:import16.FormControlName;
  _NgControl_52_6:any;
  _NgControlStatus_52_7:import14.NgControlStatus;
  _text_53:any;
  _text_54:any;
  _anchor_55:any;
  /*private*/ _appEl_55:import2.AppElement;
  _TemplateRef_55_5:any;
  _NgIf_55_6:import17.NgIf;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent0,renderType_SignupComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-4 col-md-offset-4');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_0,'h1',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Sign Up',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._FormGroupDirective_6_3 = new import13.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_6_4 = this._FormGroupDirective_6_3;
    this._NgControlStatusGroup_6_5 = new import14.NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','form-group');
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'label',(null as any));
    this.renderer.setElementAttribute(this._el_10,'for','email');
    this._text_11 = this.renderer.createText(this._el_10,'Email',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_8,'input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-control');
    this.renderer.setElementAttribute(this._el_13,'formControlName','email');
    this.renderer.setElementAttribute(this._el_13,'id','email');
    this.renderer.setElementAttribute(this._el_13,'type','email');
    this._DefaultValueAccessor_13_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3];
    this._FormControlName_13_5 = new import16.FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._FormControlName_13_5;
    this._NgControlStatus_13_7 = new import14.NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-group');
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'label',(null as any));
    this.renderer.setElementAttribute(this._el_18,'for','password');
    this._text_19 = this.renderer.createText(this._el_18,'Password ',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_21 = new import2.AppElement(21,16,this,this._anchor_21);
    this._TemplateRef_21_5 = new import20.TemplateRef_(this._appEl_21,viewFactory_SignupComponent1);
    this._NgIf_21_6 = new import17.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_23 = new import2.AppElement(23,16,this,this._anchor_23);
    this._TemplateRef_23_5 = new import20.TemplateRef_(this._appEl_23,viewFactory_SignupComponent2);
    this._NgIf_23_6 = new import17.NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_16,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-control');
    this.renderer.setElementAttribute(this._el_25,'formControlName','password');
    this.renderer.setElementAttribute(this._el_25,'id','password');
    this.renderer.setElementAttribute(this._el_25,'type','password');
    this._DefaultValueAccessor_25_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_25));
    this._NG_VALUE_ACCESSOR_25_4 = [this._DefaultValueAccessor_25_3];
    this._FormControlName_25_5 = new import16.FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_25_4);
    this._NgControl_25_6 = this._FormControlName_25_5;
    this._NgControlStatus_25_7 = new import14.NgControlStatus(this._NgControl_25_6);
    this._text_26 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','form-group radiotext');
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'label',(null as any));
    this.renderer.setElementAttribute(this._el_30,'for','usertype');
    this._text_31 = this.renderer.createText(this._el_30,'Please select if you are a:',(null as any));
    this._el_32 = this.renderer.createElement(this._el_28,'br',(null as any));
    this._text_33 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_34,'formControlName','usertype');
    this.renderer.setElementAttribute(this._el_34,'id','checkparticipant');
    this.renderer.setElementAttribute(this._el_34,'type','radio');
    this.renderer.setElementAttribute(this._el_34,'value','participant');
    this._DefaultValueAccessor_34_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_34));
    this._RadioControlValueAccessor_34_4 = new import18.RadioControlValueAccessor(this.renderer,new import19.ElementRef(this._el_34),this.parentInjector.get(import18.RadioControlRegistry),this.injector(34));
    this._NG_VALUE_ACCESSOR_34_5 = [
      this._DefaultValueAccessor_34_3,
      this._RadioControlValueAccessor_34_4
    ]
    ;
    this._FormControlName_34_6 = new import16.FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_34_5);
    this._NgControl_34_7 = this._FormControlName_34_6;
    this._NgControlStatus_34_8 = new import14.NgControlStatus(this._NgControl_34_7);
    this._text_35 = this.renderer.createText(this._el_28,' Participant',(null as any));
    this._el_36 = this.renderer.createElement(this._el_28,'br',(null as any));
    this._text_37 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_38,'formControlName','usertype');
    this.renderer.setElementAttribute(this._el_38,'type','radio');
    this.renderer.setElementAttribute(this._el_38,'value','host');
    this._DefaultValueAccessor_38_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_38));
    this._RadioControlValueAccessor_38_4 = new import18.RadioControlValueAccessor(this.renderer,new import19.ElementRef(this._el_38),this.parentInjector.get(import18.RadioControlRegistry),this.injector(38));
    this._NG_VALUE_ACCESSOR_38_5 = [
      this._DefaultValueAccessor_38_3,
      this._RadioControlValueAccessor_38_4
    ]
    ;
    this._FormControlName_38_6 = new import16.FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_38_5);
    this._NgControl_38_7 = this._FormControlName_38_6;
    this._NgControlStatus_38_8 = new import14.NgControlStatus(this._NgControl_38_7);
    this._text_39 = this.renderer.createText(this._el_28,' Host',(null as any));
    this._el_40 = this.renderer.createElement(this._el_28,'br',(null as any));
    this._text_41 = this.renderer.createText(this._el_28,'\n        ',(null as any));
    this._text_42 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','form-group');
    this._text_44 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'label',(null as any));
    this.renderer.setElementAttribute(this._el_45,'for','username');
    this.renderer.setElementAttribute(this._el_45,'id','hostname');
    this._text_46 = this.renderer.createText(this._el_45,'',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._anchor_48 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._appEl_48 = new import2.AppElement(48,43,this,this._anchor_48);
    this._TemplateRef_48_5 = new import20.TemplateRef_(this._appEl_48,viewFactory_SignupComponent3);
    this._NgIf_48_6 = new import17.NgIf(this._appEl_48.vcRef,this._TemplateRef_48_5);
    this._text_49 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._anchor_50 = this.renderer.createTemplateAnchor(this._el_43,(null as any));
    this._appEl_50 = new import2.AppElement(50,43,this,this._anchor_50);
    this._TemplateRef_50_5 = new import20.TemplateRef_(this._appEl_50,viewFactory_SignupComponent4);
    this._NgIf_50_6 = new import17.NgIf(this._appEl_50.vcRef,this._TemplateRef_50_5);
    this._text_51 = this.renderer.createText(this._el_43,'\n            ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_43,'input',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','form-control');
    this.renderer.setElementAttribute(this._el_52,'formControlName','username');
    this.renderer.setElementAttribute(this._el_52,'id','username');
    this.renderer.setElementAttribute(this._el_52,'type','text');
    this._DefaultValueAccessor_52_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_52));
    this._NG_VALUE_ACCESSOR_52_4 = [this._DefaultValueAccessor_52_3];
    this._FormControlName_52_5 = new import16.FormControlName(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_52_4);
    this._NgControl_52_6 = this._FormControlName_52_5;
    this._NgControlStatus_52_7 = new import14.NgControlStatus(this._NgControl_52_6);
    this._text_53 = this.renderer.createText(this._el_43,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._anchor_55 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_55 = new import2.AppElement(55,6,this,this._anchor_55);
    this._TemplateRef_55_5 = new import20.TemplateRef_(this._appEl_55,viewFactory_SignupComponent5);
    this._NgIf_55_6 = new import17.NgIf(this._appEl_55.vcRef,this._TemplateRef_55_5);
    this._text_56 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_57 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_58,'type','submit');
    this._text_59 = this.renderer.createText(this._el_58,'Submit\n        ',(null as any));
    this._text_60 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_61 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_6,'ngSubmit',this.eventHandler(this._handle_ngSubmit_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_6,'submit',this.eventHandler(this._handle_submit_6_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_6,'reset',this.eventHandler(this._handle_reset_6_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_6_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_6_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_25,'keyup',this.eventHandler(this._handle_keyup_25_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_1.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_2.bind(this)));
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_34,'click',this.eventHandler(this._handle_click_34_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_34,'input',this.eventHandler(this._handle_input_34_1.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_34,'blur',this.eventHandler(this._handle_blur_34_2.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_34,'change',this.eventHandler(this._handle_change_34_3.bind(this)));
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_38,'click',this.eventHandler(this._handle_click_38_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_38,'input',this.eventHandler(this._handle_input_38_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_38,'blur',this.eventHandler(this._handle_blur_38_2.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_38,'change',this.eventHandler(this._handle_change_38_3.bind(this)));
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    var disposable_16:Function = this.renderer.listen(this._el_52,'keyup',this.eventHandler(this._handle_keyup_52_0.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_52,'input',this.eventHandler(this._handle_input_52_1.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_52,'blur',this.eventHandler(this._handle_blur_52_2.bind(this)));
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._anchor_48,
      this._text_49,
      this._anchor_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._anchor_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import16.FormControlName) && (13 === requestNodeIndex))) { return this._FormControlName_13_5; }
    if (((token === import22.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import14.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7; }
    if (((token === import20.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import17.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import20.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import17.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6; }
    if (((token === import15.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_4; }
    if (((token === import16.FormControlName) && (25 === requestNodeIndex))) { return this._FormControlName_25_5; }
    if (((token === import22.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_6; }
    if (((token === import14.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_7; }
    if (((token === import15.DefaultValueAccessor) && (34 === requestNodeIndex))) { return this._DefaultValueAccessor_34_3; }
    if (((token === import18.RadioControlValueAccessor) && (34 === requestNodeIndex))) { return this._RadioControlValueAccessor_34_4; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (34 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_34_5; }
    if (((token === import16.FormControlName) && (34 === requestNodeIndex))) { return this._FormControlName_34_6; }
    if (((token === import22.NgControl) && (34 === requestNodeIndex))) { return this._NgControl_34_7; }
    if (((token === import14.NgControlStatus) && (34 === requestNodeIndex))) { return this._NgControlStatus_34_8; }
    if (((token === import15.DefaultValueAccessor) && (38 === requestNodeIndex))) { return this._DefaultValueAccessor_38_3; }
    if (((token === import18.RadioControlValueAccessor) && (38 === requestNodeIndex))) { return this._RadioControlValueAccessor_38_4; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (38 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_38_5; }
    if (((token === import16.FormControlName) && (38 === requestNodeIndex))) { return this._FormControlName_38_6; }
    if (((token === import22.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_7; }
    if (((token === import14.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_8; }
    if (((token === import20.TemplateRef) && (48 === requestNodeIndex))) { return this._TemplateRef_48_5; }
    if (((token === import17.NgIf) && (48 === requestNodeIndex))) { return this._NgIf_48_6; }
    if (((token === import20.TemplateRef) && (50 === requestNodeIndex))) { return this._TemplateRef_50_5; }
    if (((token === import17.NgIf) && (50 === requestNodeIndex))) { return this._NgIf_50_6; }
    if (((token === import15.DefaultValueAccessor) && (52 === requestNodeIndex))) { return this._DefaultValueAccessor_52_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (52 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_52_4; }
    if (((token === import16.FormControlName) && (52 === requestNodeIndex))) { return this._FormControlName_52_5; }
    if (((token === import22.NgControl) && (52 === requestNodeIndex))) { return this._NgControl_52_6; }
    if (((token === import14.NgControlStatus) && (52 === requestNodeIndex))) { return this._NgControlStatus_52_7; }
    if (((token === import20.TemplateRef) && (55 === requestNodeIndex))) { return this._TemplateRef_55_5; }
    if (((token === import17.NgIf) && (55 === requestNodeIndex))) { return this._NgIf_55_6; }
    if (((token === import13.FormGroupDirective) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._FormGroupDirective_6_3; }
    if (((token === import23.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._ControlContainer_6_4; }
    if (((token === import14.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgControlStatusGroup_6_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_6_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_6_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_13_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_13_5.ngOnChanges(changes); }
    const currVal_19:any = ((this.context.passwordchar > 0) && (this.context.passwordchar < 6));
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgIf_21_6.ngIf = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = (this.context.passwordchar < (0 - 6));
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgIf_23_6.ngIf = currVal_20;
      this._expr_20 = currVal_20;
    }
    changes = (null as any);
    const currVal_24:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._FormControlName_25_5.name = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._FormControlName_25_5.ngOnChanges(changes); }
    const currVal_36:any = 'usertype';
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._RadioControlValueAccessor_34_4.formControlName = currVal_36;
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = 'participant';
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this._RadioControlValueAccessor_34_4.value = currVal_37;
      this._expr_37 = currVal_37;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioControlValueAccessor_34_4.ngOnInit(); }
    changes = (null as any);
    const currVal_38:any = 'usertype';
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._FormControlName_34_6.name = currVal_38;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_38,currVal_38);
      this._expr_38 = currVal_38;
    }
    if ((changes !== (null as any))) { this._FormControlName_34_6.ngOnChanges(changes); }
    const currVal_50:any = 'usertype';
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._RadioControlValueAccessor_38_4.formControlName = currVal_50;
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = 'host';
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._RadioControlValueAccessor_38_4.value = currVal_51;
      this._expr_51 = currVal_51;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioControlValueAccessor_38_4.ngOnInit(); }
    changes = (null as any);
    const currVal_52:any = 'usertype';
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._FormControlName_38_6.name = currVal_52;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_52,currVal_52);
      this._expr_52 = currVal_52;
    }
    if ((changes !== (null as any))) { this._FormControlName_38_6.ngOnChanges(changes); }
    const currVal_60:any = ((this.context.usernamechar > 0) && (this.context.usernamechar < 6));
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this._NgIf_48_6.ngIf = currVal_60;
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = (this.context.usernamechar < (0 - 24));
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this._NgIf_50_6.ngIf = currVal_61;
      this._expr_61 = currVal_61;
    }
    changes = (null as any);
    const currVal_65:any = 'username';
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this._FormControlName_52_5.name = currVal_65;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_65,currVal_65);
      this._expr_65 = currVal_65;
    }
    if ((changes !== (null as any))) { this._FormControlName_52_5.ngOnChanges(changes); }
    const currVal_72:any = this.context.host;
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this._NgIf_55_6.ngIf = currVal_72;
      this._expr_72 = currVal_72;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_6_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_6_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_6_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_6_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_6_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_6_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._NgControlStatus_13_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_13_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_13_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_13_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_13_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_13_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_25:any = this._NgControlStatus_25_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_25,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_25_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_25,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_25_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_25,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_25_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_25,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_25_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_25,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_25_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_25,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_39:any = this._NgControlStatus_34_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_34,'ng-untouched',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_34_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_34,'ng-touched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_34_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_34,'ng-pristine',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_34_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_34,'ng-dirty',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_34_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_34,'ng-valid',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_34_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_34,'ng-invalid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_53:any = this._NgControlStatus_38_8.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_38,'ng-untouched',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_38_8.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_38,'ng-touched',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_38_8.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_38,'ng-pristine',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_38_8.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_38,'ng-dirty',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_38_8.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_38,'ng-valid',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_38_8.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_38,'ng-invalid',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = import4.interpolate(1,'',this.context.usernameLabel,' ');
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setText(this._text_46,currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_66:any = this._NgControlStatus_52_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_52,'ng-untouched',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_52_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_52,'ng-touched',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_52_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_52,'ng-pristine',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_52_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_52,'ng-dirty',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_52_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_52,'ng-valid',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_71:any = this._NgControlStatus_52_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_52,'ng-invalid',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_73:boolean = !this.context.myForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementProperty(this._el_58,'disabled',currVal_73);
      this._expr_73 = currVal_73;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_13_5.ngOnDestroy();
    this._FormControlName_25_5.ngOnDestroy();
    this._RadioControlValueAccessor_34_4.ngOnDestroy();
    this._FormControlName_34_6.ngOnDestroy();
    this._RadioControlValueAccessor_38_4.ngOnDestroy();
    this._FormControlName_38_6.ngOnDestroy();
    this._FormControlName_52_5.ngOnDestroy();
  }
  private _handle_ngSubmit_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_6_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_6_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_6_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_25_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_34_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.typeChange(this._el_34.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_34_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_34_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_34_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._RadioControlValueAccessor_34_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_34_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioControlValueAccessor_34_4.onChange()) !== false);
    return (true && pd_0);
  }
  private _handle_click_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.typeChange(this._el_38.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_38_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_38_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_38_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_38_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._RadioControlValueAccessor_38_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_38_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioControlValueAccessor_38_4.onChange()) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_52_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.inputCounter()) !== false);
    return (true && pd_0);
  }
  private _handle_input_52_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_52_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_52_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_52_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignupComponent> {
  if ((renderType_SignupComponent === (null as any))) { (renderType_SignupComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/auth/signup.component.html',0,import10.ViewEncapsulation.Emulated,styles_SignupComponent,{})); }
  return new _View_SignupComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent1,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'(char left: ',this.parent.context.passwordchar,')');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent2,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','danger');
    this._text_1 = this.renderer.createText(this._el_0,'(max char: 12)',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignupComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent3,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'(char left: ',this.parent.context.usernamechar,')');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent4,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','danger');
    this._text_1 = this.renderer.createText(this._el_0,'(max char: 30)',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_SignupComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _DefaultValueAccessor_5_3:import15.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_5_4:any[];
  _FormControlName_5_5:import16.FormControlName;
  _NgControl_5_6:any;
  _NgControlStatus_5_7:import14.NgControlStatus;
  _text_6:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent5,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','form-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this.renderer.setElementAttribute(this._el_2,'for','hostcode');
    this._text_3 = this.renderer.createText(this._el_2,'Host Code',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-control');
    this.renderer.setElementAttribute(this._el_5,'formControlName','hostcode');
    this.renderer.setElementAttribute(this._el_5,'id','hostcode');
    this.renderer.setElementAttribute(this._el_5,'type','password');
    this._DefaultValueAccessor_5_3 = new import15.DefaultValueAccessor(this.renderer,new import19.ElementRef(this._el_5));
    this._NG_VALUE_ACCESSOR_5_4 = [this._DefaultValueAccessor_5_3];
    this._FormControlName_5_5 = new import16.FormControlName((<_View_SignupComponent0>this.parent)._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_5_4);
    this._NgControl_5_6 = this._FormControlName_5_5;
    this._NgControlStatus_5_7 = new import14.NgControlStatus(this._NgControl_5_6);
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_5,'input',this.eventHandler(this._handle_input_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'blur',this.eventHandler(this._handle_blur_5_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.DefaultValueAccessor) && (5 === requestNodeIndex))) { return this._DefaultValueAccessor_5_3; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_4; }
    if (((token === import16.FormControlName) && (5 === requestNodeIndex))) { return this._FormControlName_5_5; }
    if (((token === import22.NgControl) && (5 === requestNodeIndex))) { return this._NgControl_5_6; }
    if (((token === import14.NgControlStatus) && (5 === requestNodeIndex))) { return this._NgControlStatus_5_7; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = 'hostcode';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._FormControlName_5_5.name = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._FormControlName_5_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatus_5_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatus_5_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_5_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_5_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_5_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_5_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_5_5.ngOnDestroy();
  }
  private _handle_input_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_SignupComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent5(viewUtils,parentInjector,declarationEl);
}