/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.radiotext[_ngcontent-%COMP%], label[_ngcontent-%COMP%], span[_ngcontent-%COMP%] {\n            color: white;\n        }\n        input.ng-invalid.ng-touched[_ngcontent-%COMP%] {\n            border: 1px solid red;\n            color: darkred;\n        }\n        span.danger[_ngcontent-%COMP%] {\n            color: #D23029;\n        }'];