/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './my-events.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../auth/auth.service';
import * as import9 from '../../acts/act.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './my-events.component.css.shim';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from './my-events-detail/my-events-detail.component';
import * as import19 from './my-events-detail/my-events-detail.component.ngfactory';
var renderType_MyEventsComponent_Host:import0.RenderComponentType = (null as any);
class _View_MyEventsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyEventsComponent_0_4:import3.MyEventsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsComponent_Host0,renderType_MyEventsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-events',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyEventsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyEventsComponent_0_4 = new import3.MyEventsComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.ActService),this.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._MyEventsComponent_0_4,[],compView_0);
    compView_0.create(this._MyEventsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MyEventsComponent) && (0 === requestNodeIndex))) { return this._MyEventsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._MyEventsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyEventsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyEventsComponent_Host === (null as any))) { (renderType_MyEventsComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_MyEventsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyEventsComponentNgFactory:import12.ComponentFactory<import3.MyEventsComponent> = new import12.ComponentFactory<import3.MyEventsComponent>('my-events',viewFactory_MyEventsComponent_Host0,import3.MyEventsComponent);
const styles_MyEventsComponent:any[] = [import13.styles];
var renderType_MyEventsComponent:import0.RenderComponentType = (null as any);
class _View_MyEventsComponent0 extends import1.AppView<import3.MyEventsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import14.NgIf;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import14.NgIf;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgFor_14_6:import15.NgFor;
  _text_15:any;
  _text_16:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsComponent0,renderType_MyEventsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'    \n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','row');
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-md-12');
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import2.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import16.TemplateRef_(this._appEl_8,viewFactory_MyEventsComponent1);
    this._NgIf_8_6 = new import14.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_10 = new import2.AppElement(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import16.TemplateRef_(this._appEl_10,viewFactory_MyEventsComponent2);
    this._NgIf_10_6 = new import14.NgIf(this._appEl_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_6,'  \n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_14 = new import2.AppElement(14,2,this,this._anchor_14);
    this._TemplateRef_14_5 = new import16.TemplateRef_(this._appEl_14,viewFactory_MyEventsComponent3);
    this._NgFor_14_6 = new import15.NgFor(this._appEl_14.vcRef,this._TemplateRef_14_5,this.parentInjector.get(import17.IterableDiffers),this.ref);
    this._text_15 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import14.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import16.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import14.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6; }
    if (((token === import16.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import15.NgFor) && (14 === requestNodeIndex))) { return this._NgFor_14_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:boolean = !this.context.isAHost();
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_8_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.isAHost();
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_10_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    changes = (null as any);
    const currVal_2:any = this.context.acts;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgFor_14_6.ngForOf = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._NgFor_14_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_14_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MyEventsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MyEventsComponent> {
  if ((renderType_MyEventsComponent === (null as any))) { (renderType_MyEventsComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/my/my-events/my-events.component.html',0,import11.ViewEncapsulation.Emulated,styles_MyEventsComponent,{})); }
  return new _View_MyEventsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MyEventsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsComponent1,renderType_MyEventsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'h1',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12');
    this._text_1 = this.renderer.createText(this._el_0,'Events Joined',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_MyEventsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyEventsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_MyEventsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsComponent2,renderType_MyEventsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'h1',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-12');
    this._text_1 = this.renderer.createText(this._el_0,'Events Created',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_MyEventsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyEventsComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_MyEventsComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyEventsDetailComponent_0_4:import18.MyEventsDetailComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsComponent3,renderType_MyEventsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'my-events-detail',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import19.viewFactory_MyEventsDetailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyEventsDetailComponent_0_4 = new import18.MyEventsDetailComponent(this.parent.parentInjector.get(import8.AuthService),this.parent.parentInjector.get(import9.ActService),this.parent.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._MyEventsDetailComponent_0_4,[],compView_0);
    compView_0.create(this._MyEventsDetailComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.MyEventsDetailComponent) && (0 === requestNodeIndex))) { return this._MyEventsDetailComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._MyEventsDetailComponent_0_4.act = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyEventsComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyEventsComponent3(viewUtils,parentInjector,declarationEl);
}