/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './my-events-detail.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../auth/auth.service';
import * as import9 from '../../../acts/act.service';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './my-events-detail.component.css.shim';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/common/src/pipes/date_pipe';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/core/src/i18n/tokens';
import * as import18 from '@angular/core/src/security';
var renderType_MyEventsDetailComponent_Host:import0.RenderComponentType = (null as any);
class _View_MyEventsDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyEventsDetailComponent_0_4:import3.MyEventsDetailComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsDetailComponent_Host0,renderType_MyEventsDetailComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-events-detail',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyEventsDetailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyEventsDetailComponent_0_4 = new import3.MyEventsDetailComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.ActService),this.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._MyEventsDetailComponent_0_4,[],compView_0);
    compView_0.create(this._MyEventsDetailComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MyEventsDetailComponent) && (0 === requestNodeIndex))) { return this._MyEventsDetailComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyEventsDetailComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyEventsDetailComponent_Host === (null as any))) { (renderType_MyEventsDetailComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_MyEventsDetailComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyEventsDetailComponentNgFactory:import12.ComponentFactory<import3.MyEventsDetailComponent> = new import12.ComponentFactory<import3.MyEventsDetailComponent>('my-events-detail',viewFactory_MyEventsDetailComponent_Host0,import3.MyEventsDetailComponent);
const styles_MyEventsDetailComponent:any[] = [import13.styles];
var renderType_MyEventsDetailComponent:import0.RenderComponentType = (null as any);
class _View_MyEventsDetailComponent0 extends import1.AppView<import3.MyEventsDetailComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import14.NgIf;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  _pipe_date_0:import15.DatePipe;
  _pipe_date_0_0:any;
  _pipe_date_0_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsDetailComponent0,renderType_MyEventsDetailComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','col-md-4 box');
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','thumbnail');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'img',(null as any));
    this.renderer.setElementAttribute(this._el_5,'alt','');
    this._text_6 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','caption');
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','title');
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'h6',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','startdate');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_7,'h6',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','url');
    this._el_16 = this.renderer.createElement(this._el_15,'a',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_7,'p',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','description');
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','button');
    this._text_24 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_25 = new import2.AppElement(25,23,this,this._anchor_25);
    this._TemplateRef_25_5 = new import16.TemplateRef_(this._appEl_25,viewFactory_MyEventsDetailComponent1);
    this._NgIf_25_6 = new import14.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_28 = this.renderer.createText(this._el_23,'\n      ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_32 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._pipe_date_0 = new import15.DatePipe(this.parentInjector.get(import17.LOCALE_ID));
    this._pipe_date_0_0 = import4.pureProxy2(this._pipe_date_0.transform.bind(this._pipe_date_0));
    this._pipe_date_0_1 = import4.pureProxy2(this._pipe_date_0.transform.bind(this._pipe_date_0));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import14.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_6:any = this.context.isAHost();
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_25_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.act.thumbnail,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_5,'src',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.act.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    valUnwrapper.reset();
    const currVal_2:any = import4.interpolate(2,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,this._pipe_date_0.transform)(this.context.act.starttime,'dd/MM/yy HH:mm')),' - ',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_1,this._pipe_date_0.transform)(this.context.act.endtime,'dd/MM/yy HH:mm')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this.renderer.setText(this._text_13,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.act.websiteurl,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_16,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.act.websiteurl,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_17,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.act.details,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_20,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_MyEventsDetailComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MyEventsDetailComponent> {
  if ((renderType_MyEventsDetailComponent === (null as any))) { (renderType_MyEventsDetailComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/my/my-events/my-events-detail/my-events-detail.component.html',0,import11.ViewEncapsulation.Emulated,styles_MyEventsDetailComponent,{})); }
  return new _View_MyEventsDetailComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MyEventsDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyEventsDetailComponent1,renderType_MyEventsDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-warning');
    this._text_1 = this.renderer.createText(this._el_0,'Edit Event',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.editEvent()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MyEventsDetailComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyEventsDetailComponent1(viewUtils,parentInjector,declarationEl);
}