/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './header.component.css.shim';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/security';
import * as import19 from '@angular/router/src/directives/router_link_active';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from './dropdown.directive';
var renderType_HeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import3.HeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent_Host0,renderType_HeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import3.HeaderComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeaderComponent_Host === (null as any))) { (renderType_HeaderComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_HeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeaderComponentNgFactory:import11.ComponentFactory<import3.HeaderComponent> = new import11.ComponentFactory<import3.HeaderComponent>('app-header',viewFactory_HeaderComponent_Host0,import3.HeaderComponent);
const styles_HeaderComponent:any[] = [import12.styles];
var renderType_HeaderComponent:import0.RenderComponentType = (null as any);
class _View_HeaderComponent0 extends import1.AppView<import3.HeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import13.RouterLinkWithHref;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import14.NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import14.NgIf;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent0,renderType_HeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','navbar navbar-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container-fluid');
    this._text_3 = this.renderer.createText(this._el_2,'\n    \n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','navbar-header');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_7,'class','navbar-toggle collapsed');
    this.renderer.setElementAttribute(this._el_7,'data-target','#bs-example-navbar-collapse-1');
    this.renderer.setElementAttribute(this._el_7,'data-toggle','collapse');
    this.renderer.setElementAttribute(this._el_7,'type','button');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','sr-only');
    this._text_10 = this.renderer.createText(this._el_9,'Toggle navigation',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','icon-bar');
    this._text_13 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','icon-bar');
    this._text_15 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_7,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','icon-bar');
    this._text_17 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','navbar-brand');
    this._RouterLinkWithHref_19_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._el_20 = this.renderer.createElement(this._el_19,'img',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','logo');
    this.renderer.setElementAttribute(this._el_20,'src','http://i.imgur.com/Xe51Afc.png');
    this._text_21 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','collapse navbar-collapse');
    this.renderer.setElementAttribute(this._el_24,'id','bs-example-navbar-collapse-1');
    this._text_25 = this.renderer.createText(this._el_24,'\n      \n      ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_26 = new import2.AppElement(26,24,this,this._anchor_26);
    this._TemplateRef_26_5 = new import17.TemplateRef_(this._appEl_26,viewFactory_HeaderComponent1);
    this._NgIf_26_6 = new import14.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_24,'\n\n      ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._appEl_28 = new import2.AppElement(28,24,this,this._anchor_28);
    this._TemplateRef_28_5 = new import17.TemplateRef_(this._appEl_28,viewFactory_HeaderComponent2);
    this._NgIf_28_6 = new import14.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_24,'\n\n    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_2,'\n\n  ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import17.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import14.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    if (((token === import17.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import14.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    const currVal_3:boolean = !this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_26_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.isLoggedIn();
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_28_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_19_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_19_3.ngOnDestroy();
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeaderComponent> {
  if ((renderType_HeaderComponent === (null as any))) { (renderType_HeaderComponent = viewUtils.createRenderComponentType('/Users/alex/code/wdi/project/gowhere/assets/app/header/header.component.html',0,import10.ViewEncapsulation.Emulated,styles_HeaderComponent,{})); }
  return new _View_HeaderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _RouterLinkActive_4_3:import19.RouterLinkActive;
  _query_RouterLink_4_0:import20.QueryList<any>;
  _query_RouterLinkWithHref_4_1:import20.QueryList<any>;
  _el_5:any;
  _RouterLinkWithHref_5_3:import13.RouterLinkWithHref;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkActive_8_3:import19.RouterLinkActive;
  _query_RouterLink_8_0:import20.QueryList<any>;
  _query_RouterLinkWithHref_8_1:import20.QueryList<any>;
  _el_9:any;
  _RouterLinkWithHref_9_3:import13.RouterLinkWithHref;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _arr_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent1,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','nav navbar-nav navbar-right');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'li',(null as any));
    this.renderer.setElementAttribute(this._el_4,'routerLinkActive','active');
    this._RouterLinkActive_4_3 = new import19.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_4),this.renderer);
    this._query_RouterLink_4_0 = new import20.QueryList<any>();
    this._query_RouterLinkWithHref_4_1 = new import20.QueryList<any>();
    this._el_5 = this.renderer.createElement(this._el_4,'a',(null as any));
    this._RouterLinkWithHref_5_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parentInjector.get(import16.LocationStrategy));
    this._text_6 = this.renderer.createText(this._el_5,'Sign Up',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'li',(null as any));
    this.renderer.setElementAttribute(this._el_8,'routerLinkActive','active');
    this._RouterLinkActive_8_3 = new import19.RouterLinkActive(this.parent.parentInjector.get(import9.Router),new import21.ElementRef(this._el_8),this.renderer);
    this._query_RouterLink_8_0 = new import20.QueryList<any>();
    this._query_RouterLinkWithHref_8_1 = new import20.QueryList<any>();
    this._el_9 = this.renderer.createElement(this._el_8,'a',(null as any));
    this._RouterLinkWithHref_9_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parentInjector.get(import16.LocationStrategy));
    this._text_10 = this.renderer.createText(this._el_9,'Log In',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n      ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkWithHref_5_3; }
    if (((token === import19.RouterLinkActive) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._RouterLinkActive_4_3; }
    if (((token === import13.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3; }
    if (((token === import19.RouterLinkActive) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkActive_8_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._RouterLinkActive_4_3.routerLinkActive = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_4_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_2:any = this._arr_0('/signup');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_5_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_5_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkActive_8_3.routerLinkActive = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_8_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_6:any = this._arr_1('/signin');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._RouterLinkWithHref_9_3.routerLink = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_9_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_4_0.dirty) {
        this._query_RouterLink_4_0.reset([]);
        this._RouterLinkActive_4_3.links = this._query_RouterLink_4_0;
        this._query_RouterLink_4_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_4_1.dirty) {
        this._query_RouterLinkWithHref_4_1.reset([this._RouterLinkWithHref_5_3]);
        this._RouterLinkActive_4_3.linksWithHrefs = this._query_RouterLinkWithHref_4_1;
        this._query_RouterLinkWithHref_4_1.notifyOnChanges();
      }
      if (this._query_RouterLink_8_0.dirty) {
        this._query_RouterLink_8_0.reset([]);
        this._RouterLinkActive_8_3.links = this._query_RouterLink_8_0;
        this._query_RouterLink_8_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_8_1.dirty) {
        this._query_RouterLinkWithHref_8_1.reset([this._RouterLinkWithHref_9_3]);
        this._RouterLinkActive_8_3.linksWithHrefs = this._query_RouterLinkWithHref_8_1;
        this._query_RouterLinkWithHref_8_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_4_3.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_8_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._RouterLinkWithHref_5_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_5,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_7:any = this._RouterLinkWithHref_9_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_9,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_7));
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_5_3.ngOnDestroy();
    this._RouterLinkActive_4_3.ngOnDestroy();
    this._RouterLinkWithHref_9_3.ngOnDestroy();
    this._RouterLinkActive_8_3.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_5_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_9_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _DropdownDirective_2_3:import22.DropdownDirective;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import13.RouterLinkWithHref;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import14.NgIf;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  /*private*/ _expr_2:any;
  _arr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent2,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','nav navbar-nav navbar-right');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'li',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','dropdown');
    this.renderer.setElementAttribute(this._el_2,'rbDropdown','');
    this._DropdownDirective_2_3 = new import22.DropdownDirective();
    this._text_3 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'a',(null as any));
    this.renderer.setElementAttribute(this._el_4,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_4,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_4,'class','dropdown-toggle');
    this.renderer.setElementAttribute(this._el_4,'role','button');
    this._text_5 = this.renderer.createText(this._el_4,'User ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','caret');
    this._text_7 = this.renderer.createText(this._el_2,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_2,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','dropdown-menu');
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'li',(null as any));
    this._el_11 = this.renderer.createElement(this._el_10,'a',(null as any));
    this._RouterLinkWithHref_11_3 = new import13.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parentInjector.get(import16.LocationStrategy));
    this._text_12 = this.renderer.createText(this._el_11,'My Events',(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_8,'li',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_15 = new import2.AppElement(15,14,this,this._anchor_15);
    this._TemplateRef_15_5 = new import17.TemplateRef_(this._appEl_15,viewFactory_HeaderComponent3);
    this._NgIf_15_6 = new import14.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_8,'li',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','divider');
    this.renderer.setElementAttribute(this._el_17,'role','separator');
    this._text_18 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_8,'li',(null as any));
    this._el_20 = this.renderer.createElement(this._el_19,'a',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Logout',(null as any));
    this._text_22 = this.renderer.createText(this._el_8,'\n          ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'mouseleave',this.eventHandler(this._handle_mouseleave_2_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3; }
    if (((token === import17.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import14.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import22.DropdownDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._DropdownDirective_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_4:any = this._arr_0('/myevents');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_11_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_11_3.ngOnChanges(changes); }
    const currVal_6:any = this.parent.context.isAHost();
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_15_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._DropdownDirective_2_3.opened;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'open',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._RouterLinkWithHref_11_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_11,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_11_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DropdownDirective_2_3.open()) !== false);
    return (true && pd_0);
  }
  private _handle_mouseleave_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DropdownDirective_2_3.close()) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_11_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onLogout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HeaderComponent3 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import13.RouterLinkWithHref;
  _text_1:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeaderComponent3,renderType_HeaderComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this._RouterLinkWithHref_0_3 = new import13.RouterLinkWithHref(this.parent.parent.parentInjector.get(import9.Router),this.parent.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parent.parentInjector.get(import16.LocationStrategy));
    this._text_1 = this.renderer.createText(this._el_0,'Create Event',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('/new');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeaderComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeaderComponent3(viewUtils,parentInjector,declarationEl);
}